name:                how-monochromatic
version:             0.1.0.0
github:              "SebTee/how-monochromatic"
license:             BSD3
author:              "Sebastian Tee"
maintainer:          "seb.tom.tee@gmail.com"
copyright:           "2021 Sebastian Tee"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/SebTee/how-monochromatic#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  how-monochromatic-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - how-monochromatic

tests:
  how-monochromatic-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - how-monochromatic
