name:                how-monochromatic
version:             0.1.0.0
github:              "SebTee/how-monochromatic"
license:             MIT
author:              "Sebastian Tee"
maintainer:          "seb.tom.tee@gmail.com"
copyright:           "2022 Sebastian Tee"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/SebTee/how-monochromatic#readme>

dependencies:
- base >= 4.7 && < 5
- containers > 0.6

library:
  source-dirs: src

executables:
  howmono:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - how-monochromatic

tests:
  how-monochromatic-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - how-monochromatic
    - hspec >= 2.0

verbatim: |
  foreign-library libhowmono
    type:                native-shared
    if os(Windows)
      options: standalone
    other-modules:
        Paths_how_monochromatic
      , Clib
      , BCG 
      , ParseBCG
    ghc-options: -threaded
    build-depends:
        base >=4.7 && <5
      , containers >0.6
      , how-monochromatic
    hs-source-dirs:      src
    default-language:    Haskell2010
